    /*
    *
============================================================================
    *  Name     : TBitmap.h
    *  Part of  : Example3D
    *  Created  : 12/14/2003 by Forum Nokia
    *  Description:
    *     This is the project specification file for Example3D.
    *     Initial content was generated by Series 60 AppWizard.
    *
    *  Version  : 1.0.0
    *  Copyright: Forum Nokia
    *
============================================================================
    */

#ifndef __TBITMAP_H__
#define __TBITMAP_H__

// INCLUDES
#include <e32std.h>
#include <gdi.h>

// CLASS DECLARATION

/**
*  Very simple bitmap type used by this example
*  Contains only pixel data, size and color format
*/

class TBitmap
	{
	public:

		TAny* iData;
		TSize iSize;
		TDisplayMode iMode;
	};


#endif
